# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 05:11
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20150710_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
