# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20160117_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('homepage', models.CharField(max_length=1000)),
                ('category_list', models.CharField(max_length=1000)),
                ('funding_total_usd', models.BigIntegerField()),
                ('status', models.CharField(max_length=144)),
                ('country_code', models.CharField(max_length=144)),
                ('state_code', models.CharField(max_length=144)),
                ('region', models.CharField(max_length=144)),
                ('city', models.CharField(max_length=144)),
                ('funding_rounds', models.IntegerField()),
                ('founded_at', models.DateTimeField()),
                ('first_funding_at', models.DateTimeField()),
                ('last_funding_at', models.DateTimeField()),
            ],
        ),
    ]
