# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='funding_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='funding_total_usd',
            field=models.BigIntegerField(default=0),
        ),
    ]
