# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20160117_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='funding_rounds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='funding_total_usd',
            field=models.BigIntegerField(null=True),
        ),
    ]
