# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20160117_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='homepage',
            new_name='homepage_url',
        ),
        migrations.AddField(
            model_name='company',
            name='market',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='first_funding_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='founded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_funding_at',
            field=models.DateTimeField(null=True),
        ),
    ]
