# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20160117_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='acquisitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_permalink', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=1000)),
                ('company_category_list', models.CharField(max_length=1000)),
                ('company_market', models.CharField(max_length=1000)),
                ('company_country_code', models.CharField(max_length=1000)),
                ('company_state_code', models.CharField(max_length=1000)),
                ('company_region', models.CharField(max_length=1000)),
                ('company_city', models.CharField(max_length=1000)),
                ('acquirer_permalink', models.CharField(max_length=1000)),
                ('acquirer_name', models.CharField(max_length=1000)),
                ('acquirer_category_list', models.CharField(max_length=1000)),
                ('acquirer_market', models.CharField(max_length=1000)),
                ('acquirer_country_code', models.CharField(max_length=1000)),
                ('acquirer_state_code', models.CharField(max_length=1000)),
                ('acquirer_region', models.CharField(max_length=1000)),
                ('acquirer_city', models.CharField(max_length=1000)),
                ('acquired_at', models.DateTimeField(null=True)),
                ('acquired_month', models.DateTimeField(null=True)),
                ('price_amount', models.DateTimeField(null=True)),
                ('price_currency_code', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='additions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('month_str', models.DateTimeField(null=True)),
                ('year_str', models.IntegerField(null=True)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_permalink', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=1000)),
                ('company_category_list', models.CharField(max_length=1000)),
                ('company_market', models.CharField(max_length=1000)),
                ('company_country_code', models.CharField(max_length=1000)),
                ('company_state_code', models.CharField(max_length=1000)),
                ('company_region', models.CharField(max_length=1000)),
                ('company_city', models.CharField(max_length=1000)),
                ('investor_permalink', models.CharField(max_length=1000)),
                ('investor_name', models.CharField(max_length=1000)),
                ('investor_category_list', models.DateTimeField(null=True)),
                ('investor_market', models.DateTimeField(null=True)),
                ('investor_country_code', models.DateTimeField(null=True)),
                ('investor_state_code', models.DateTimeField(null=True)),
                ('investor_region', models.DateTimeField(null=True)),
                ('investor_city', models.DateTimeField(null=True)),
                ('funding_round_permalink', models.CharField(max_length=1000)),
                ('funding_round_type', models.CharField(max_length=1000)),
                ('funding_round_code', models.DateTimeField(null=True)),
                ('funded_at', models.DateTimeField(null=True)),
                ('raised_amount_usd', models.IntegerField(null=True)),
            ],
        ),
    ]
