# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_acquisitions_additions_investments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acquisitions',
            new_name='acquisition',
        ),
        migrations.RenameModel(
            old_name='additions',
            new_name='addition',
        ),
        migrations.RenameModel(
            old_name='investments',
            new_name='investment',
        ),
    ]
